/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataSewa;

import javax.swing.DefaultComboBoxModel;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author MSI GAMING
 */
public class FormPenyewaan extends javax.swing.JFrame {

    /**
     * Creates new form FormPenyewaan
     */
    public FormPenyewaan() {
        initComponents();
        loadJenisKendaraan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJenisKendaraan = new javax.swing.JLabel();
        lblTipeKendaraan = new javax.swing.JLabel();
        lblTanggalSewa = new javax.swing.JLabel();
        lblTanggalKembali = new javax.swing.JLabel();
        cbJenisKendaraan = new javax.swing.JComboBox<>();
        cbTipeKendaraan = new javax.swing.JComboBox<>();
        txtTanggalKembali = new javax.swing.JTextField();
        txtTanggalSewa = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenyewaan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Penyewaan Kendaraan");

        lblNama.setForeground(new java.awt.Color(51, 51, 51));
        lblNama.setText("Nama");

        lblJenisKendaraan.setForeground(new java.awt.Color(51, 51, 51));
        lblJenisKendaraan.setText("Jenis Kendaraan");

        lblTipeKendaraan.setForeground(new java.awt.Color(51, 51, 51));
        lblTipeKendaraan.setText("Tipe Kendaraan");

        lblTanggalSewa.setForeground(new java.awt.Color(51, 51, 51));
        lblTanggalSewa.setText("Tanggal Sewa");

        lblTanggalKembali.setForeground(new java.awt.Color(51, 51, 51));
        lblTanggalKembali.setText("Tanggal Kembali");

        cbJenisKendaraan.setBackground(new java.awt.Color(255, 255, 255));
        cbJenisKendaraan.setForeground(new java.awt.Color(51, 51, 51));

        cbTipeKendaraan.setBackground(new java.awt.Color(255, 255, 255));
        cbTipeKendaraan.setForeground(new java.awt.Color(51, 51, 51));
        cbTipeKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipeKendaraanActionPerformed(evt);
            }
        });

        txtTanggalKembali.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalKembali.setForeground(new java.awt.Color(255, 255, 255));

        txtTanggalSewa.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalSewa.setForeground(new java.awt.Color(255, 255, 255));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setForeground(new java.awt.Color(51, 51, 51));
        btnSimpan.setText("Simpan");

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setForeground(new java.awt.Color(51, 51, 51));
        btnEdit.setText("Edit");

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setForeground(new java.awt.Color(51, 51, 51));
        btnHapus.setText("Hapus");

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.setForeground(new java.awt.Color(51, 51, 51));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        tblPenyewaan.setBackground(new java.awt.Color(255, 255, 255));
        tblPenyewaan.setForeground(new java.awt.Color(51, 51, 51));
        tblPenyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis Kendaraan", "Tipe Kendaraan", "Plat Nomor", "Tanggal Sewa", "Tanggal Kembali", "Total Biaya"
            }
        ));
        jScrollPane1.setViewportView(tblPenyewaan);

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Keterangan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJenisKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipeKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbJenisKendaraan, 0, 310, Short.MAX_VALUE)
                            .addComponent(cbTipeKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTanggalKembali)
                            .addComponent(lblTanggalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTanggalSewa)
                            .addComponent(txtTanggalKembali)))
                    .addComponent(txtNama))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(379, 379, 379))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenisKendaraan)
                    .addComponent(cbJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTanggalSewa)
                    .addComponent(txtTanggalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipeKendaraan)
                    .addComponent(cbTipeKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTanggalKembali)
                    .addComponent(txtTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(54, 54, 54)
                        .addComponent(btnEdit)
                        .addGap(51, 51, 51)
                        .addComponent(btnHapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cbTipeKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipeKendaraanActionPerformed
        String jenisKendaraan = (String) cbJenisKendaraan.getSelectedItem();
        
        // Jika jenis kendaraan dipilih, update cbTipeKendaraan
        if (jenisKendaraan != null && !jenisKendaraan.isEmpty()) {
            updateTipeKendaraan(jenisKendaraan);
        }
    }//GEN-LAST:event_cbTipeKendaraanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenyewaan().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenisKendaraan;
    private javax.swing.JComboBox<String> cbTipeKendaraan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJenisKendaraan;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTanggalKembali;
    private javax.swing.JLabel lblTanggalSewa;
    private javax.swing.JLabel lblTipeKendaraan;
    private javax.swing.JTable tblPenyewaan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggalKembali;
    private javax.swing.JTextField txtTanggalSewa;
    // End of variables declaration//GEN-END:variables

    
    private void loadJenisKendaraan() {
        String[] jenisKendaraan = {"", "Motor", "Mobil"};
        cbJenisKendaraan.setModel(new DefaultComboBoxModel<>(jenisKendaraan));

        // Menambahkan ItemListener untuk memperbarui tipe kendaraan secara otomatis
        cbJenisKendaraan.addItemListener((java.awt.event.ItemEvent evt) -> {
            // Panggil updateTipeKendaraan hanya jika jenis kendaraan dipilih
            String jenisKendaraan1 = (String) cbJenisKendaraan.getSelectedItem();
            if (jenisKendaraan1 != null && !jenisKendaraan1.trim().isEmpty()) {
                updateTipeKendaraan(jenisKendaraan1);
            }
        });   
    }
    
    private void updateTipeKendaraan(String jenisKendaraan) {
        DefaultComboBoxModel<String> tipeModel = new DefaultComboBoxModel<>();
    
        String query = "SELECT tipe_kendaraan FROM kendaraan WHERE jenis_kendaraan = ?";

        try (Connection conn = DatabaseSewa.getConnection();
             PreparedStatement ps = conn.prepareStatement(query)) {

            ps.setString(1, jenisKendaraan);
            ResultSet rs = ps.executeQuery();

            // Cek apakah query mengembalikan hasil
            boolean dataFound = false;
            while (rs.next()) {
                dataFound = true;
                String tipeKendaraan = rs.getString("tipe_kendaraan");
                tipeModel.addElement(tipeKendaraan);
            }

            // Jika tidak ada data ditemukan
            if (!dataFound) {
                JOptionPane.showMessageDialog(this, "Tidak ada tipe kendaraan untuk jenis ini.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

            // Update combo box
            SwingUtilities.invokeLater(() -> cbTipeKendaraan.setModel(tipeModel));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                    "Terjadi kesalahan saat mengambil data tipe kendaraan.\n" + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
    
